version: "3"
services:
  code:
    restart: always
    build: ./docker-build
    ports: ["8000:80"]
    # volumes: ["./docker-build/code:/var/www/html"]
    environment:
      - LC_ALL=C.UTF-8
    links:
      - db

  db:
    image: mysql
    ports: ["3306:3306"]
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: UMD_CTF_DB_PW
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro