# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: challenge.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='challenge.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x63hallenge.proto\"\n\n\x08get_flag\"\x19\n\tsend_flag\x12\x0c\n\x04\x66lag\x18\x01 \x02(\t')
)




_GET_FLAG = _descriptor.Descriptor(
  name='get_flag',
  full_name='get_flag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=29,
)


_SEND_FLAG = _descriptor.Descriptor(
  name='send_flag',
  full_name='send_flag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='send_flag.flag', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['get_flag'] = _GET_FLAG
DESCRIPTOR.message_types_by_name['send_flag'] = _SEND_FLAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

get_flag = _reflection.GeneratedProtocolMessageType('get_flag', (_message.Message,), dict(
  DESCRIPTOR = _GET_FLAG,
  __module__ = 'challenge_pb2'
  # @@protoc_insertion_point(class_scope:get_flag)
  ))
_sym_db.RegisterMessage(get_flag)

send_flag = _reflection.GeneratedProtocolMessageType('send_flag', (_message.Message,), dict(
  DESCRIPTOR = _SEND_FLAG,
  __module__ = 'challenge_pb2'
  # @@protoc_insertion_point(class_scope:send_flag)
  ))
_sym_db.RegisterMessage(send_flag)


# @@protoc_insertion_point(module_scope)
